
services:
  app:
    container_name: minimart_app
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - minimart_network
    depends_on:
      - db
      - redis

networks:
  minimart_network:
    external: true