FROM openjdk:21-jdk

# Copy jar
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

COPY .env.dev .

# Correct ENTRYPOINT with separated arguments
ENTRYPOINT ["java","-jar", "/app.jar", "--spring.profiles.active=dev"]
