### server health check -> protect endpoint
GET http://localhost:8080/api/v1/healthz
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidGFtYW1odWRhIiwiZXhwIjoxNzUzODM0MDk3LCJpYXQiOjE3NTM4MzM3OTcsInJvbGVzIjpbIlJPTEVfQ1VTVE9NRVIiXX0.nGc5TTXZls7TkZA-msL3Jz6nvMz102Kg9xN3J5hkz8Q

### test dto validation
POST http://localhost:8080/api/v1/test/1?filter=
Content-Type: application/json

{
  "message": "Hello World"
}

### auth login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "tamamhda@gmail.com",
  "password": "password"

}

### auth register user
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "full_name": "tamam huda",
  "username": "tamamhuda",
  "email": "tamamhda@gmail.com",
  "password": "password",
  "confirm_password": "password"

}

### auth current user authenticated
GET http://localhost:8080/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidGFtYW1odWRhIiwiZXhwIjoxNzU0MDA4MzA0LCJpYXQiOjE3NTQwMDgwMDQsInJvbGVzIjpbIlJPTEVfQ1VTVE9NRVIiXX0.ZGCDjtsi5VLo4gcCVMKPRMCNvWt3e9S71zTn3Ym54XQ

### refresh access token
POST http://localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidGFtYW1odWRhIiwiZXhwIjoxNzU0NjE0NTg1LCJpYXQiOjE3NTQwMDk3ODV9.p-H873--LVNJ8cufm6MbEKwtbcL3NWOfYKxB_oBdk4E"
}

### auth logout
POST http://localhost:8080/api/v1/auth/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidGFtYW1odWRhIiwiZXhwIjoxNzU0MDEwMDk1LCJpYXQiOjE3NTQwMDk3OTUsInJvbGVzIjpbIlJPTEVfQ1VTVE9NRVIiXX0.NX9GgMVJsUStOvUt1rFkxeQNC-BRO-adb-Z2DKTZHIw"
}