server:
  port: ${APP_PORT}
  servlet:
    context-path: "/api/v1"

spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:file:.env

  security:
    user:
      name: admin
      password: admin