# Base configuration (common for all profiles)
server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: "/api/v1"

spring:
  application:
    name: ${APP_NAME:my-app}


  output:
    ansi:
      enabled: always

  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    open-in-view: off

  security:
    user:
      name: admin
      password: admin
    jwt:
      access:
        secret-key: ${JWT_ACCESS_SECRET}
        expiration-in-minutes: ${JWT_ACCESS_EXPIRATION_IN_MINUTES:15}
      refresh:
        secret-key: ${JWT_REFRESH_SECRET}
        expiration-in-days: ${JWT_REFRESH_EXPIRATION_IN_DAYS:7}

  cloud:
    config:
      aws:
        credentials:
          access-key: ${AWS_ACCESS_KEY}
          secret-key: ${AWS_SECRET_KEY}
        s3:
          region: ${AWS_S3_REGION:us-east-1}
          bucket: ${AWS_S3_BUCKET}

  xendit:
    secret-key: ${XENDIT_SECRET_KEY}
    webhook-verification-token: ${XENDIT_VERIFICATION_TOKEN}

  jackson:
    property-naming-strategy: SNAKE_CASE

  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: ${REDIS_KEY_PREFIX:app}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      database: ${REDIS_DB:0}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false

  mailtrap:
    token: ${MAILTRAP_TOKEN}
    sender-email: ${MAILTRAP_SENDER_EMAIL}
    template:
      verification_email_id: ${MAILTRAP_TEMPLATE_VERIFICATION_EMAIL_ID}
      verification_url: ${MAILTRAP_TEMPLATE_VERIFICATION_URL}

  totp:
    global-secret: ${TOTP_GLOBAL_SECRET}
    expiration-in-minutes: ${TOTP_EXPIRY_IN_MINUTES:5}

bucket4j:
  enabled: true
  key-prefix: "buckets"
  redis-address: ${REDIS_ADDRESS:redis://localhost:6379}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /api-docs

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
