server:
  port: 8080
  servlet:
    context-path: "/api/v1"

spring:
  application:
    name: test-app
  config:
    activate:
      on-profile: test

  flyway:
    enabled: false

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    open-in-view: off

  sql:
    init:
      mode: always

  security:
    user:
      name: admin
      password: admin
    jwt:
      access:
        secret-key: dummy-access-secret
        expiration-in-minutes: 15
      refresh:
        secret-key: dummy-refresh-secret
        expiration-in-days: 7

  cloud:
    config:
      aws:
        credentials:
          access-key: dummy-access-key
          secret-key: dummy-secret-key
        s3:
          region: us-east-1
          bucket: dummy-bucket

  xendit:
    secret-key: dummy-xendit-secret
    webhook-verification-token: dummy-token
    redirect:
      success-url: https://localhost:8080/api/v1/webhook/payment
      failure-url: https://localhost:8080/api/v1/webhook/payment

  jackson:
    property-naming-strategy: SNAKE_CASE

  cache:
    type: none
    redis:
      use-key-prefix: true
      key-prefix: app

  data:
    redis:
      host: localhost
      database: 0
      port: 6379
      repositories:
        enabled: false

  mailtrap:
    token: dummy-mailtrap-token
    sender-email: dummy@example.com
    template:
      verification_email_id: dummy-template-id
      verification_url: http://localhost:8080/api/v1/auth/verify

  totp:
    global-secret: dummy-global-secret
    expiration-in-minutes: 5

bucket4j:
  enabled: false
  key-prefix: "buckets"
  redis-address: redis://localhost:6379

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: ERROR
    org.springframework: ERROR