server:
  port: ${APP_PORT}
  servlet:
    context-path: "/api/v1"

spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:file:.env

  security:
    user:
      name: admin
      password: admin

    jwt:
      access:
        secret-key: ${JWT_ACCESS_SECRET}
        expiration-in-minutes: ${JWT_ACCESS_EXPIRATION_IN_MINUTES}
      refresh:
        secret-key: ${JWT_REFRESH_SECRET}
        expiration-in-days: ${JWT_REFRESH_EXPIRATION_IN_DAYS}

  cloud:
    config:
      aws:
        credentials:
          access-key: ${AWS_ACCESS_KEY}
          secret-key: ${AWS_SECRET_KEY}
        s3:
          region: ${AWS_S3_REGION}
          bucket: ${AWS_S3_BUCKET}

  xendit:
    secret-key: ${XENDIT_SECRET_KEY}
    redirect:
      success-url: http://localhost:8080/api/v1/webhook/payment
      failure-url: http://localhost:8080/api/v1/webhook/payment/failure
