server:
  port: ${APP_PORT}
  servlet:
    context-path: "/api/v1"

spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:file:.env

  security:
    user:
      name: admin
      password: admin

    jwt:
      access:
        secret-key: ${JWT_ACCESS_SECRET}
        expiration-in-minutes: ${JWT_ACCESS_EXPIRATION_IN_MINUTES}
      refresh:
        secret-key: ${JWT_REFRESH_SECRET}
        expiration-in-days: ${JWT_REFRESH_EXPIRATION_IN_DAYS}

  cloud:
    config:
      aws:
        credentials:
          access-key: ${AWS_ACCESS_KEY}
          secret-key: ${AWS_SECRET_KEY}
        s3:
          region: ${AWS_S3_REGION}
          bucket: ${AWS_S3_BUCKET}

  xendit:
    secret-key: ${XENDIT_SECRET_KEY}
    webhook-verification-token: ${XENDIT_VERIFICATION_TOKEN}
    redirect:
      success-url: http://localhost:8080/api/v1/webhook/payment
      failure-url: http://localhost:8080/api/v1/webhook/payment/failure
  jackson:
    property-naming-strategy: SNAKE_CASE

  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: ${REDIS_KEY_PREFIX}


  data:
    redis:
      host: ${REDIS_HOST}
      database: ${REDIS_DB}
      port: ${REDIS_PORT}
      repositories:
        enabled: false

  mailtrap:
    token: ${MAILTRAP_TOKEN}
    sender-email: ${MAILTRAP_SENDER_EMAIL}
    template:
      verification_email_id: ${MAILTRAP_TEMPLATE_VERIFICATION_EMAIL_ID}
      verification_url: ${MAILTRAP_TEMPLATE_VERIFICATION_URL}

  totp:
    global-secret: ${TOTP_GLOBAL_SECRET}
    expiration-in-minutes: ${TOTP_EXPIRY_IN_MINUTES}