
### auth login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "tamamhxx",
  "password": "password"
}

### auth register user
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "full_name": "Tamam huda",
  "username": "tamamhxx",
  "email": "tamamhuda11@gmail.com",
  "password": "password",
  "confirm_password": "password"
}

### refresh access token
POST http://localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
  "token": "{{token.refresh_token}}"
}

### auth logout
POST http://localhost:8080/api/v1/auth/logout
Content-Type: application/json

{
  "token": "{{token.access_token}}"
}

### resend email verification
POST http://localhost:8080/api/v1/auth/resend-verification
Authorization: Bearer {{token.access_token}}