### add cart item
POST {{baseUrl}}/{{version}}/cart/items
Content-Type: application/json
Authorization: Bearer {{token.access_token}}

{
  "product_id": "51907b1b-5d38-4b4c-8278-e4c00643a884",
  "quantity": 3
}

### update cart item
PUT {{baseUrl}}/{{version}}/cart/items/b64523bc-fff4-4a96-a362-cb6c633eb9c4
Content-Type: application/json
Authorization: Bearer {{token.access_token}}

{
  "quantity": 2
}

### get user cart
GET {{baseUrl}}/{{version}}/cart
Authorization: Bearer {{token.access_token}}

### get cart item
GET {{baseUrl}}/{{version}}/cart/items/0bc462be-e2b1-48fd-95b1-84cd38fe87ba
Authorization: Bearer {{token.access_token}}

### delete cart item from cart
DELETE {{baseUrl}}/{{version}}/cart/items/4a3ca507-a000-4630-885d-da24b48885e4
Authorization: Bearer {{token.access_token}}