### add cart item
POST {{baseUrl}}/{{version}}/cart/items
Content-Type: application/json
Authorization: Bearer {{token.access_token}}

{
  "product_id": "e860c8d2-9c41-4809-98bd-0e7ea3ff502a",
  "quantity": 3
}

### update cart item
PUT {{baseUrl}}/{{version}}/cart/items/f0ef0afc-1e82-4abf-bc32-dafb015c9890
Content-Type: application/json
Authorization: Bearer {{token.access_token}}

{
  "quantity": 2
}

### get user cart
GET {{baseUrl}}/{{version}}/cart
Authorization: Bearer {{token.access_token}}

### get cart item
GET {{baseUrl}}/{{version}}/cart/items/0bc462be-e2b1-48fd-95b1-84cd38fe87ba
Authorization: Bearer {{token.access_token}}

### delete cart item from cart
DELETE {{baseUrl}}/{{version}}/cart/items/4a3ca507-a000-4630-885d-da24b48885e4
Authorization: Bearer {{token.access_token}}