### checkout by cart items
POST {{baseUrl}}/{{version}}/orders/checkout
Content-Type: application/json
Authorization: Bearer {{token.access_token}}

{
  "cart_items_ids": [
      "29172b46-ca15-4ed5-8c92-a6b5e3f53432"
  ]
}

### get all user's orders
GET {{baseUrl}}/{{version}}/orders
Content-Type: application/json
Authorization: Bearer {{token.access_token}}

### get order by id
GET {{baseUrl}}/{{version}}/orders/931641db-f342-4d10-b331-d04ec81bfdfa
Authorization: Bearer {{token.access_token}}