### checkout by cart items
POST {{baseUrl}}/{{version}}/orders/checkout
Content-Type: application/json
Authorization: Bearer {{token.access_token}}

{
  "cart_items_ids": [
      "b64523bc-fff4-4a96-a362-cb6c633eb9c4"
  ]
}

### get all user's orders
GET {{baseUrl}}/{{version}}/orders
Content-Type: application/json
Authorization: Bearer {{token.access_token}}

### get order by id
GET {{baseUrl}}/{{version}}/orders/931641db-f342-4d10-b331-d04ec81bfdfa
Authorization: Bearer {{token.access_token}}