
### create product
POST {{baseUrl}}/{{version}}/products
Content-Type: application/json
Authorization: Bearer {{token.access_token}}

{
  "name": "Product 1",
  "description": "Best #1 product",
  "stock_quantity": 5,
  "price": 50000,
  "category": "skincare"
}

### get product by id
GET {{baseUrl}}/{{version}}/products/cef11db0-2415-4fe2-a8da-e85b395fd310

### update product
PUT {{baseUrl}}/{{version}}/products/e860c8d2-9c41-4809-98bd-0e7ea3ff502a
Content-Type: application/json

{
  "price": 75000
}

### delete product
DELETE {{baseUrl}}/{{version}}/products/0e407594-3707-47a5-b849-b51d95347e59

### get all product with optional filter -> category, minPrice, maxPrice
GET {{baseUrl}}/{{version}}/products

### upload product image
POST http://localhost:8080/api/v1/products/20ccdbc9-78aa-4b1c-9336-36a30a153237/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="sample.jpg"
Content-Type: image/jpeg

< ./sample.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### stream product image
GET http://localhost:8080/api/v1/products/20ccdbc9-78aa-4b1c-9336-36a30a153237/images/0d613ea3-1c96-4eea-b3d0-91f82684ad5f-sample.jpg
